# Generated by Django 3.2 on 2022-11-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
